// src/app/task-component/task.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'task',
  templateUrl: './task.component.html',
  styleUrls: ['./task.component.scss']
})
export class Task implements OnInit {
  @Input() list;
  count:number = 0;
  currentTask;

  constructor(){

  }   
  ngOnInit(){
  
  }

  /**
   * Used to change the list name.
   * @param event The current event object.
   */
  updateList(event) {
      if(event.key === "Enter") {
          this.list.name = event.target.value;
      }
  }

  /**
   * When a new task is added the task object is added to the list array.
   * @param event The current event object.
   */
  addTask(input) {
      var task = {
          name:input.value,
          id:this.list.tasks.length,
          subTasks:[]
      };
      this.list.tasks.push(task);
      input.value = "";
  }

  /**
   * When the task is clicked the currenttask object is modified to 
   * the clicked task object.
   * @param task Object of the clicked task.
   */
  changeTask(task) {
      this.currentTask = task;
  }

 /**
  * The clicked task object status is changed.
  * @param task Object of the clicked task.
  */
  finishTask(task) {
      task.isComplete = task.isComplete ? false : true;
  }
}
<div class="task-component">
    <div id="todo-list" class="todo-task-list">
        <a id="info" class="info">
            <div id = "list-title" class="task-title">
                <input class="task-title-input" type="text" value={{list.name}} (keyup)="updateList($event)"/>
            </div>
        </a>
        <div id="task-container">
            <div *ngFor = "let task of list.tasks">
                <div class="added-task">
                    <div (click)="finishTask(task)">
                        <a *ngIf = "!task.isComplete">
                            <i class='material-icons tick-icon'>check_circle_outline</i>
                        </a>
                        <a *ngIf = "task.isComplete">
                            <i class='material-icons tick-icon'>check_circle</i>
                        </a>
                    </div>
                    <div [ngClass]="task.isComplete ? 'completed-task-name' : 'task-name'" (click)="changeTask(task)">
                            <p>{{task.name}}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="add-new-task">
            <a id="add-task-icon" href="#add-new-task">
                <i class="material-icons new-task-icon">add</i>
            </a>
            <input #addNewTask class="add-task-input" type="text" 
                placeholder="Add task" (keyup.enter)="addTask(addNewTask)"/>   
        </div>
    </div>
    <div>
        <app-sub-task [task]="currentTask" [list] = "list"></app-sub-task>
    </div>
</div>

// src/js/components/Task.jsx
import React, { Component } from "react";
import { connect } from "react-redux";
import uuidv1 from "uuid";
import TaskContainer from "./TaskContainer.jsx";
import { addTasks } from "../actions/index";


/**
 * Used to connect  currentList object from redux state to the components props.
 * 
 * @param {*} dispatch 
 */
function mapStateToProps(state) {
    return { currentList: state.currentList };
};


/**
 * Used to connect addTasks action function to the components props.
 * 
 * @param {*} dispatch 
 */
function mapDispatchToProps(dispatch) {
    return {
        addTasks: state => dispatch(addTasks(state))
    };
}

class TaskComponent extends Component {
    constructor() {
        super();
        this.addTask = this.addTask.bind(this);
    }

    /**
     * Used to add task in tasks array maintained in the currentList object in redux state. 
     * The created task object is passed through action to the reducer.
     */
    addTask(event) {
        if (event.key === 'Enter') {
            const title = event.target.value;
            const id = uuidv1();
            const subTasks = [];
            this.props.addTasks({ title, id, subTasks });
        }
    }

    render() {
        return (
            <div id="todo-list" className="todo-task-list">
                <TaskContainer />
                <div className="add-new-task">
                    <a id="add-task-icon" href="#add-new-task">
                        <i className="material-icons new-task-icon">add</i>
                    </a>  
                    <input className="add-task-input" type="text"  onKeyDown={this.addTask}/>   
                </div>
            </div>
        );
    }
}

const Task = connect(mapStateToProps, mapDispatchToProps)(TaskComponent);
export default Task;
